"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['upload.py']
DATA_FILES = [
	'resources'
]
OPTIONS = {
	'iconfile':'settings/UploadLogo.icns',
	'plist':'settings/Info.plist'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    version='1.1',
    author='Radartech',
    setup_requires=['py2app']
)